output.elasticsearch: 
  hosts: ["elasticsearch:9200"] 
 
setup.kibana:
  host: "kibana:5601"

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

#output.logstash:
#  hosts: ['logstash:5044']
#  

#filebeat.prospectors:
#- input_type: log
#  paths:
#    - /hostfs/var/log

#filebeat.prospectors:
#    - paths:
#        - my_json.log
#      fields_under_root: true
#      fields:
#        tags: ['json']
