version: '3.5'

services:
#    apm:
#        container_name: apm
#        dns: 10.3.1.1
#        dns_search:
#            - ubuntu.home
#            - home
#        environment:
#            setup.kibana.host: kibana:5601
#        hostname: apm
#        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/apm-server:${APM_VERSION:-7.12.1}
#        labels:
#            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
#            co.elastic.metrics/metricsets: status
#            co.elastic.metrics/module: apm
#            co.elastic.metrics/period: 10s
#        links:
#            - elasticsearch:elasticsearch
#            - kibana:kibana
#        logging:
#            driver: json-file
#            options:
#                max-file: "3"
#                max-size: "10m"
#        networks:
#            - elk-net
#        ports:
#            - "8200:8200"
#        restart: unless-stopped
#        volumes:
#            - ./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
#            - ./apm/log:/var/log:rw
#
#    auditbeat:
#        cap_add:
#            - ALL
#        container_name: auditbeat
#        dns: 10.3.1.1
#        dns_search:
#            - ubuntu.home
#            - home
#        environment:
#            SETUP_KIBANA_HOST: kibana:5601
#        hostname: auditbeat
#        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/auditbeat:${AUDITBEAT_VERSION:-7.12.1}
#        labels:
#            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
#            co.elastic.metrics/metricsets: status
#            co.elastic.metrics/module: auditbeat
#            co.elastic.metrics/period: 10s
#        links:
#            - elasticsearch:elasticsearch
#            - kibana:kibana
#        logging:
#            driver: json-file
#            options:
#                max-file: "3"
#                max-size: "10m"
#        networks:
#            - elk-net
##        ports:
##            - "8200:8200"
#        restart: unless-stopped
#        volumes:
#            - ./auditbeat/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml:ro
#            - ./auditbeat/log:/var/log:rw
       
    elasticsearch:
        container_name: elasticsearch
#        depends_on:
#            - kibana
        dns: 10.3.1.1
        dns_search:
            - ubuntu.home
            - home
        environment:
            cluster.name: 'docker-cluster'
            bootstrap.memory_lock: 'true'
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            discovery.type: single-node
            node.name:    elasticsearch
            network.host: elasticsearch
            http.port: 9200
#            xpack.security.enabled: 'true'
        hostname: elasticsearch
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/elasticsearch:${ELASTICSEARCH_VERSION:-7.13.0}
        labels:
            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
            co.elastic.metrics/metricsets: status
            co.elastic.metrics/module: elasticsearch
            co.elastic.metrics/period: 10s
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - elk-net
        ports:
            - "9200:9200"
            - "9300:9300"
        restart: unless-stopped
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
            - ./elasticsearch/log:/var/log


#    filebeat:
#        container_name: filebeat
#        dns: 10.3.1.1
#        dns_search:
#            - ubuntu.home
#            - home
#        environment:
#            SETUP_KIBANA_HOST: kibana:5601
#        hostname: filebeat
#        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/filebeat:${FILEBEAT_VERSION:-7.12.1}
#        labels:
#            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
#            co.elastic.metrics/metricsets: status
#            co.elastic.metrics/module: filebeat
#            co.elastic.metrics/period: 10s
#        links:
#            - elasticsearch:elasticsearch
#            - kibana:kibana
#        logging:
#            driver: json-file
#            options:
#                max-file: "3"
#                max-size: "10m"
#        networks:
#            - elk-net
#        restart: unless-stopped
#        volumes:
#            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#            - ./filebeat/modules.d:/usr/share/filebeat/modules.d:ro
#            - ./filebeat/log:/var/log:rw
#            - /var/lib/docker/containers:/var/lib/docker/containers:ro
#            - /var/run/docker.sock:/var/run/docker.sock
#            - /var/log:/hostfs/var/log:ro
#
#    journalbeat:
#        container_name: journalbeat
#        dns: 10.3.1.1
#        dns_search:
#            - ubuntu.home
#            - home
##        entrypoint: /bin/cat
#        environment:
#            SETUP_KIBANA_HOST: kibana:5601
##        stdin_open: true
##        tty: true
#        hostname: journalbeat
#        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/journalbeat:${JOURNALBEAT_VERSION:-7.12.1}
#        labels:
#            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
#            co.elastic.metrics/metricsets: status
#            co.elastic.metrics/module: journalbeat
#            co.elastic.metrics/period: 10s
#        links:
#            - elasticsearch:elasticsearch
#            - kibana:kibana
#        logging:
#            driver: json-file
#            options:
#                max-file: "3"
#                max-size: "10m"
#        networks:
#            - elk-net
#        restart: unless-stopped
#        volumes:
#            - /var/log:/host:ro
#            - ./journalbeat/journalbeat.yml:/usr/share/journalbeat/journalbeat.yml:ro
#            - ./journalbeat/log:/var/log:rw
#        user: root

    kibana:
        container_name: kibana
        dns: 10.3.1.1
        dns_search:
            - ubuntu.home
            - home
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
            SERVER_NAME: kibana
        hostname: kibana
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/kibana:${KIBANA_VERSION:-7.13.0}
        labels:
            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
            co.elastic.metrics/metricsets: status
            co.elastic.metrics/module: kibana
            co.elastic.metrics/period: 10s
        links:
            - elasticsearch:elasticsearch
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - elk-net
        ports:
            - "5601:5601"
        restart: unless-stopped
        volumes:
            - ./kibana/kibana.yml:/etc/kibana/config/kibana.yml:ro
            - ./kibana/log:/var/log

    logstash:
        container_name: logstash
#        command: "logstash -r -f /usr/share/logstash/config/logstash.yml"
#        command: bash -c "bin/logstash-plugin install logstash-filter-metricize && logstash -f /etc/logstash/conf.d/logstash.conf "
        dns: 10.3.1.1
        dns_search:
            - ubuntu.home
            - home
        environment:
            SETUP_KIBANA_HOST: kibana:5601
        hostname: logstash
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/logstash:${LOGSTASH_VERSION:-7.13.0}
        labels:
            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
            co.elastic.metrics/metricsets: status
            co.elastic.metrics/module: logstash
            co.elastic.metrics/period: 10s
        links:
            - elasticsearch:elasticsearch
            - kibana:kibana
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - elk-net
        ports:
            - "514:5514"
            - "514:5514/udp"
            - "515:5515"
            - "5044:5044"
            - "9600:9600"
            - "8080:8080"
        restart: unless-stopped
        volumes:
            - ./logstash/patterns:/usr/share/logstash/patterns
            - ./logstash/config:/usr/share/logstash/config
            - ./logstash/pipelines:/usr/share/logstash/pipelines
            - ./logstash/log:/var/log

    metricbeat:
        container_name: metricbeat
        dns: 10.3.1.1
        dns_search:
            - ubuntu.home
            - home
        environment:
             SETUP_KIBANA_HOST: kibana:5601
        hostname: metricbeat
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/metricbeat:${METRICBEAT_VERSION:-7.13.0}
        labels:
            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
            co.elastic.metrics/metricsets: status
            co.elastic.metrics/module: metricbeat
            co.elastic.metrics/period: 10s
        links:
            - elasticsearch:elasticsearch
            - kibana:kibana
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - elk-net
        restart: unless-stopped
        user: root
        volumes:
            - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
#            - ./metricbeat/metricbeat.yml:/etc/metricbeat/metricbeat.yml:ro
            - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d:ro
            - ./metricbeat/log:/var/log
#            - /var/run/docker.sock:/var/run/docker.sock
            - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
            - /proc:/hostfs/proc:ro
            - /:/hostfs:ro

networks:
   elk-net:
       name: elk-container-net
