version: '3.5'

services:
    filebeat:
        container_name: filebeat
        environment:
            setup.kibana.host: kibana:5601
        extra_hosts:
            - "elasticsearch:10.1.3.15"
            - "kibana:10.1.3.15"
        hostname: filebeat
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/filebeat:${FILEBEAT_VERSION:-7.5.1}
        labels:
            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
            co.elastic.metrics/metricsets: status
            co.elastic.metrics/module: filebeat
            co.elastic.metrics/period: 10s
        links:
            - elasticsearch:elasticsearch
            - kibana:kibana
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - elk-net
        restart: unless-stopped
        volumes:
            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
            - ./filebeat/modules.d:/usr/share/filebeat/modules.d:ro
            - ./filebeat/log:/var/log:rw
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/log:/hostfs/var/log:ro

    journalbeat:
#        entrypoint: /bin/cat
#        stdin_open: true
#        tty: true
        container_name: journalbeat
        extra_hosts:
            - "elasticsearch:10.1.3.15"
            - "kibana:10.1.3.15"
        hostname: journalbeat
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/journalbeat:${JOURNALBEAT_VERSION:-7.5.1}
        labels:
            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
            co.elastic.metrics/metricsets: status
            co.elastic.metrics/module: journalbeat
            co.elastic.metrics/period: 10s
        links:
            - elasticsearch:elasticsearch
            - kibana:kibana
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - elk-net
        restart: unless-stopped
        volumes:
            - /var/log:/host:ro
            - ./journalbeat/journalbeat.yml:/usr/share/journalbeat/journalbeat.yml:ro
            - ./journalbeat/log:/var/log:rw
        user: root

    logstash:
        container_name: logstash
        extra_hosts:
            - "elasticsearch:10.1.3.15"
            - "kibana:10.1.3.15"
        hostname: logstash
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/logstash:${LOGSTASH_VERSION:-7.5.1}
        labels:
            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
            co.elastic.metrics/metricsets: status
            co.elastic.metrics/module: logstash
            co.elastic.metrics/period: 10s
        links:
            - elasticsearch:elasticsearch
            - kibana:kibana
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - elk-net
        restart: unless-stopped
        volumes:
            - ./logstash/logstash.yml:/etc/logstash/logstash.yml:ro
            - ./logstash/pipeline/:/etc/logstash/pipeline/
            - ./logstash/log:/var/log

    metricbeat:
        container_name: metricbeat
        extra_hosts:
            - "elasticsearch:10.1.3.15"
            - "kibana:10.1.3.15"
        hostname: metricbeat
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/metricbeat:${METRICBEAT_VERSION:-7.5.1}
        labels:
            co.elastic.metrics/hosts: '$${data.host}:$${data.port}'
            co.elastic.metrics/metricsets: status
            co.elastic.metrics/module: metricbeat
            co.elastic.metrics/period: 10s
        links:
            - elasticsearch:elasticsearch
            - kibana:kibana
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - elk-net
        restart: unless-stopped
        user: root
        volumes:
            - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
#            - ./metricbeat/metricbeat.yml:/etc/metricbeat/metricbeat.yml:ro
            - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d:ro
            - ./metricbeat/log:/var/log
            - /var/run/docker.sock:/var/run/docker.sock
            - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
            - /proc:/hostfs/proc:ro
            - /:/hostfs:ro

networks:
   elk-net:
       name: elk-container-net
