# Module: logstash
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.3/metricbeat-module-logstash.html

- module: logstash
  metricsets:
    - _node
    - _node/stats
  period: 10s
  hosts: ["http://logstash:9600"]
  #username: "user"
  #password: "secret"
