# Module: zookeeper
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.3/metricbeat-module-zookeeper.html

- module: zookeeper
  #metricsets:
  #  - mntr
  #  - server
  period: 10s
  hosts: ["10.1.3.6:2181","10.1.3.10:2181","10.1.3.11:2181"]
