
#setup.kibana.host: "kibana:5601"

#config.reload.automatic: true
#config.reload.interval: 5s
#config.debug: trace

#modules:
#  - name: syslog

#log.level: trace
#log.format: json

monitoring.enabled: true
xpack.management.enabled: false
xpack.monitoring.enabled: false
