
#setup.kibana.host: "kibana:5601"

#config.reload.automatic: true
#config.reload.interval: 5s
#config.debug: trace

#modules:
#  - name: syslog

#log.level: trace
#log.format: json

monitoring.enabled: true
monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
#xpack.management.enabled: false
#xpack.monitoring.enabled: false
#xpack.management.elasticsearch.hosts: ["https://elasticsearch:9200"]
#xpack.monitoring.collection.config.enabled: true