
#setup.kibana.host: "kibana:5601"

#config.reload.automatic: true
#config.reload.interval: 5s
#config.debug: true

#log.level: trace
#log.format: json

monitoring.enabled: true
monitoring.elasticsearch.hosts: ['http://${ELASTICSEARCH_HOSTS:elasticsearch:9200}']
pipeline.ordered: false
pipeline.ecs_compatibility: disabled

#xpack.management.enabled: true
#xpack.monitoring.enabled: true
#xpack.management.elasticsearch.hosts: ['http://${ELASTICSEARCH_HOSTS:elasticsearch:9200}']
#xpack.monitoring.collection.config.enabled: true