# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: beats-pipeline
  path.config: "/usr/share/logstash/pipelines/beats.conf"
  pipeline.workers: 2
- pipeline.id: http-pipeline
  path.config: "/usr/share/logstash/pipelines/http.conf"
  pipeline.workers: 2
- pipeline.id: syslog_pipeline
  path.config: "/usr/share/logstash/pipelines/syslog.conf"
  pipeline.workers: 3
- pipeline.id: nginx_error_pipeline
  path.config: "/usr/share/logstash/pipelines/nginx_error.conf"
  pipeline.workers: 1
- pipeline.id: nginx_access_pipeline
  path.config: "/usr/share/logstash/pipelines/nginx_access.conf"
  pipeline.workers: 1
- pipeline.id: jenkins_pipeline
  path.config: "/usr/share/logstash/pipelines/jenkins.conf"
  pipeline.workers: 1
- pipeline.id: microk8s_pipeline
  path.config: "/usr/share/logstash/pipelines/microk8s.conf"
  pipeline.workers: 1
- pipeline.id: docker_registry_pipeline
  path.config: "/usr/share/logstash/pipelines/docker-registry.conf"
  pipeline.workers: 1
- pipeline.id: other_pipeline
  path.config: "/usr/share/logstash/pipelines/other.conf"
  pipeline.workers: 1
