output.elasticsearch: 
  hosts: ["elasticsearch:9200"] 
 
setup.kibana:
  host: "kibana:5601"

output.stdout.codec.rubydebug.metadata: true

input {
  beats {
    port => 5044
  }   
}   

filter {
  if [tags][json] {
    json {
      source => "message"
    }   
  }   
}   
